[package]
name = "yield_aggregator"
version = "1.0.0"
language = "2"

[addresses]
YieldAggregator = "_"

[dev-addresses]
executor_auth = "0x100"
executor_v2 = "0x101"
layerzero = "0x102"
layerzero_apps = "0x103"
layerzero_common = "0x104"
msglib_auth = "0x105"
msglib_routing_helper = "0x106"
msglib_v1_1 = "0x107"
msglib_v2 = "0x108"
msglib_v2_1 = "0x109"
msglib_v3 = "0x10a"
uln_301 = "0x10b"
zro = "0x10c"


[dependencies]
AptosFramework = { local = "aptos-core-main/aptos-move/framework/aptos-framework" }
AptosTokenObjects = { local = "aptos-core-main/aptos-move/framework/aptos-token-objects" }
layerzero_apps = { local = "LayerZero-Aptos-Contract-main/layerzero-apps" }

[dev-dependencies]
